### PR TITLE
remove backend normalization for link users

### LINKED ISSUE #882: [Bug]  Link users sometimes silently failing
## 🐞 Description

Link users is not behaving predictably; some unknown portion of linkages that show up as "successful" from a dashboard user's perspective are not executing on the backend. The signature of this is that none of the users involved in the supposedly successful linking event have `childIds` (for teachers/caregivers) or `parentIds`/`teacherIds` fields in their userdoc where a list of linked uids should be stored.

This manifests as caregiver users not getting the child specific part of the survey (because they are not linked to a child)

## ✅ Steps to Reproduce

1. Add users
2. Link the users
3. Check if the "successfully" linked users have expected childIds/parentIds/teacherIds fields in their userdoc with the expected values; for a failed event, the fields are missing entirely.

## 📷 Screenshots / Logs

If applicable, add screenshots or paste console/network logs.

## 🌐 Environment

- OS: [e.g. macOS, Windows, iOS]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. v1.0.2]

## 🔗 Related Issues / Context

Link to any related issues, pull requests, or Slack threads.

### PR DESCRIPTION
**Pull request by CCuskley**
## Proposed changes

The userType normalization "helper" itroduced in PR #858 (it was me) over-corrected by changing child to student before sending it to the backend; this backend function is already built to handle "child". Normalization removed.

## Types of changes

What types of changes does this pull request introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Tests (new or updated tests)
- [ ] Styles (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Other (please describe below)

### CODE REVIEW

**Comment by u2234-io** [comment]
`normalizeUserTypeForBackend` is also called here: https://github.com/levante-framework/levante-dashboard/blob/main/src/pages/users/AddUsers.vue#L635

**Comment by CCuskley** [comment]
> `normalizeUserTypeForBackend` is also called here: https://github.com/levante-framework/levante-dashboard/blob/main/src/pages/users/AddUsers.vue#L635

Yep - checked that, but I think the add users function on the backend needs/expects student (before the "helper" existed it was converting child to student in place). The link users function is looking for child.

**Comment by CCuskley** [comment]
Verified that adding and linking now both work as expected

**Review by u2234-io — APPROVED** [review]

File: src/pages/users/LinkUsers.vue [hunk 1]
```diff
@@ -466,8 +465,10 @@ const submitUsers = async () => {
       if (idField) normalizedUser.id = user[idField];
       if (userTypeField) {
         const userTypeValue = user[userTypeField];
+        // Link users: send CSV userType as-is (trimmed). Do not use normalizeUserTypeForBackend —
+        // the linkUsers Cloud Function expects child rows as "child", not "student".
         normalizedUser.userType =
-          typeof userTypeValue === 'string' ? normalizeUserTypeForBackend(userTypeValue.toLowerCase()) : userTypeValue;
+          typeof userTypeValue === 'string' ? userTypeValue.trim() : userTypeValue;
```
Comment (asengupta3) [inline src/pages/users/LinkUsers.vue:471]: We need a better contract for front and backend.
