### PR TITLE
Fix: dupe group names

### LINKED ISSUE #905: [Bug]  Identical group names within a site should be prohibited
## 🐞 Description

It's still intermittently possible to create a new group with the same name as an existing group. This needs to be impossible.

## ✅ Steps to Reproduce

2. Click on '...'
3. See error: '...'

## 📷 Screenshots / Logs

If applicable, add screenshots or paste console/network logs.

## 🌐 Environment

- OS: [e.g. macOS, Windows, iOS]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. v1.0.2]

## 🔗 Related Issues / Context

Link to any related issues, pull requests, or Slack threads.

### PR DESCRIPTION
**Pull request by u2234-io**
Fixes #905.

Adds a uniqueness check to orgName w/ vuelidate in AddUsersModal.

## Types of changes

What types of changes does this pull request introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that does not add functionality but makes code cleaner or more efficient)
- [ ] Tests (new or updated tests)
- [ ] Styles (changes to code styling)
- [ ] CI (continuous integration changes)
- [ ] Other (please describe below)

### CODE REVIEW

File: src/components/modals/AddGroupModal.vue [hunk 1]
```diff
@@ -221,13 +224,33 @@ const orgTypesRequiringParent: string[] = [
...
+  existingOrgType,
+  computed(() => parentDistrict.value?.id),
+  computed(() => parentSchool.value?.id),
+  ref(null),
+  false,
+  { enabled: computed(() => !!orgType.value) },
+);
+
+const isUnique = (value: string) => {
+  if (!value) return true;
```
Comment (rolivares93) [inline src/components/modals/AddGroupModal.vue:238]: Shouldn't this return `false` for empty values?

**Review by rolivares93 — COMMENTED** [review]
LGTM! Left you a small question

File: src/components/modals/AddGroupModal.vue (hunk 1 above)
Comment (u2234-io) [reply src/components/modals/AddGroupModal.vue:238]: This is a `vuelidate` convention. When there's multiple validators they all get run, without short circuiting if one of them fails. Because "required" gets validated on line 249, if it also gets checked here the component will show both validation errors for an all-whitespace input:

```
Value is required
A site with this name already exists.
```

**Review by rolivares93 — APPROVED** [review]

**Review by CCuskley — APPROVED** [review]
Looks good to me - I can't really test because had trouble inducing this on dev, but this is all non-breaking so no blocker. Let's merge this (exception to the merge hold since it targets a bug found in QA)
